name: Build And Deploy React App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.jobs
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
        
      - name: Build 
        run: npm run build

      - name: Deploy React Project To Ansible ControlNode
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/"
          target: "/home/ubuntu/front/"

      - name: Execute Ansible Playbook
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~
            ansible-playbook -i inventory.ini docker-container-web.yml

